[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd ../.. && npm ci"]

[phases.build]
cmds = ["cd ../.. && npm run build:railway"]

[start]
cmd = "STATIC_DIR=static node dist/main.js"
